server:
  port: ${SERVER_PORT:8080}

spring:
  application:
    name: tg-bot-service
    public-prefix-path: ${TG_BOT_SERVICE_PUBLIC_URL_PREFIX:/api/tgbot}
    private-prefix-path: ${TG_BOT_SERVICE_PRIVATE_URL_PREFIX:/tgbot}
#  datasource:
#    url: ${TG_BOT_SERVICE_DB_JDBC_URL:jdbc:postgresql://localhost:5432/tg_bot_service?currentSchema=tg-bot-service&user=postgres&password=postgres}
#    driver-class-name: org.po stgresql.Driver
  jpa:
    properties:
      hibernate:
        jdbc.lob.non_contextual_creation: true
    open-in-view: false
  liquibase:
    enabled: ${TG_BOT_SERVICE_LIQUIBASE_ENABLED:false}
    change-log: classpath:db/changelog/master.xml

management:
  endpoint:
    env:
      keys-to-sanitize: spring.datasource.url, SERVICE_TEMPLATE_DB_JDBC_URL
  info:
    env:
      enabled: true
  endpoints:
    web:
      exposure:
        include: info, health, env
      path-mapping:
        info: ${spring.application.public-prefix-path}/info
        health: /health
        env: ${spring.application.private-prefix-path}/env
      base-path: # сбрасывает дефолтный маппинг актуатора

info:
  application:
    version: '@project.version@'

logging:
  pattern:
    console: "${LOG_CONSOLE_PATTERN:%d{yyyy-MM-dd HH:mm:ss.SSS} %+5level --- [%+15.15thread] %-40.40logger{36} : %msg%n}"
  level:
    ROOT: INFO
    ru.luc1o: ${TG_BOT_SERVICE_LOG_LEVEL:INFO}
    org.springframework: ${TG_BOT_SERVICE_LOG_LEVEL_SPRING:INFO}

springdoc:
  packagesToScan: ru.luc1o.tgbot
  api-docs:
    path: /swagger/v3/api-docs
  swagger-ui:
    path: /swagger-ui

bot:
  name: ${TELEGRAM_BOT_NAME:no-name}
  token: ${TELEGRAM_BOT_TOKEN:no-token}
#
#
#feign:
#  client:
#    config:
#      telegram-service:
#        bot:
#          api-url: ${BOT_API_TELEGRAM_SERVICE_HOST:http://localhost:8082}
#          api-base-url: ${BOT_API_TELEGRAM_PRIVATE_URL_PREFIX:}
#        user:
#          api-url: ${USER_API_TELEGRAM_SERVICE_HOST:http://localhost:8082}
#          api-base-url: ${USER_API_TELEGRAM_PRIVATE_URL_PREFIX:}
#      default:
#        connectTimeout: ${FEIGN_CONNECT_TIMEOUT:5000}
#        readTimeout: ${FEIGN_READ_TIMEOUT:5000}
#        loggerLevel: ${FEIGN_LOGGER_LEVEL:full}

